spring:
   profiles:
      active:
        - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
      name: mycloud-test-client-1

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:87654321@localhost:7301/eureka
  register-with-eureka: false

info:
  app.name: mycloud-config-client-dev-1
  company.name: sg
---
server:
  port: 8102

spring:
  profiles: beta
  application:
      name: mycloud-test-client

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:87654321@localhost:7301/eureka
  register-with-eureka: false
  
info:
  app.name: mycloud-config-client-beta
  company.name: sg
